[package]
name = "cli"
version = "0.1.0"
authors = ["Andrew Danger Lyon <andrew@killtheradio.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
dialoguer = "0.7.1"
dirs = "3.0.1"
glob = "0.3.0"
prettytable-rs = "0.8.0"
regex = "1.4.3"
serde = "1.0"
stamp-core = { path = "../core" }
textwrap = { version = "0.13", features = ["terminal_size"] }

